#!/usr/bin/env -S npx tsx
/**
 * @fileoverview Generates runnable Agent Fleet task packs from generated ESLint inventory markdown.
 *
 * @remarks
 * This CLI consumes the repository's `.eslint-inventory/generated/` artifact tree, especially the
 * `packages/<package>/fixes/file--*.md` file-batch pages generated by `npm run eslint:inventory`.
 * It is useful when the operator wants Agent Fleet packs based on the curated inventory backlog rather than raw
 * ESLint JSON. The generator preserves inventory context in every prompt and reuses the shared pack scaffolding:
 * prompts, per-task scripts, package sequential runners, package-parallel runner, logs folders, summaries, and
 * `COMMANDS.md`.
 *
 * @example
 * ```bash
 * npx tsx skills/agent-fleet/scripts/generate-eslint-inventory-agent-fleet-pack.ts \
 *   --inventory-root .eslint-inventory/generated \
 *   --purpose eslint-inventory-cleanup \
 *   --severity all
 * ```
 *
 * @testing CLI: npx tsx skills/agent-fleet/scripts/generate-eslint-inventory-agent-fleet-pack.ts --help
 * @see scripts/eslint-inventory/generate.ts - Produces the generated inventory markdown consumed by this CLI.
 * @see skills/agent-fleet/scripts/agent-fleet-pack-lib.ts - Shared pack writer utilities.
 * @documentation reviewed=2026-05-06 standard=FILE_OVERVIEW_STANDARDS_TYPESCRIPT@3
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import path from "node:path";
import {
  agentFleetPackSessionDir,
  agentFleetPackSlugify,
  agentFleetPackWrite,
  type AgentFleetPackDiagnostic,
  type AgentFleetPackPackageConfig,
  type AgentFleetPackTask,
} from "./agent-fleet-pack-lib";

/**
 * Severity filter for including inventory file batches when the operator limits error vs warning noise.
 */
type SeverityFilter = "all" | "error" | "warning";

/**
 * Parsed CLI options for workspace paths, inventory selection, output layout, and parallel agent caps.
 */
type CliOptions = {
  readonly inventoryRoot: string;
  readonly workspaceRoot: string;
  readonly outRoot: string;
  readonly purpose: string;
  readonly model: string;
  readonly severity: SeverityFilter;
  readonly packageFilters: ReadonlySet<string>;
  readonly parallelStrategy: "package" | "none" | "bounded";
  readonly maxConcurrentTasks: number;
  readonly maxConcurrentTasksPerPackage: number;
  readonly agentLaunchDelaySeconds: number;
};

/**
 * One generated inventory markdown page plus the structured diagnostics extracted for a single source file.
 */
type InventoryFileBatch = {
  readonly packageName: string;
  readonly repoRelativePath: string;
  readonly inventoryPagePath: string;
  readonly diagnostics: readonly AgentFleetPackDiagnostic[];
  readonly severities: readonly string[];
};

/** CLI entrypoint. */
function main(): void {
  const options = parseArgs(process.argv.slice(2));
  const inventoryRoot = path.resolve(options.workspaceRoot, options.inventoryRoot);
  if (!existsSync(inventoryRoot)) {
    throw new Error(`Inventory root not found: ${options.inventoryRoot}. Run npm run eslint:inventory first or pass --inventory-root.`);
  }

  const batches = readInventoryBatches({ ...options, inventoryRoot });
  const packageConfigs = buildPackageConfigs(options.workspaceRoot, batches);
  const tasks = batches.map((batch, index) => toTask({ batch, index, packageConfigs, workspaceRoot: options.workspaceRoot }));
  const sessionDir = agentFleetPackSessionDir(options.outRoot, options.purpose);

  const result = agentFleetPackWrite({
    workspaceRoot: options.workspaceRoot,
    sessionDir,
    model: options.model,
    purposeSlug: options.purpose,
    packageConfigs,
    tasks,
    contextNote:
      "Generated ESLint inventory markdown has been converted into bounded Agent Fleet tasks. Use the inventory page as curated context, fix the scoped file findings, and preserve runtime behavior and documentation quality.",
    parallelStrategy: options.parallelStrategy,
    maxConcurrentTasks: options.maxConcurrentTasks,
    maxConcurrentTasksPerPackage: options.maxConcurrentTasksPerPackage,
    agentLaunchDelaySeconds: options.agentLaunchDelaySeconds,
  });

  console.log(result.sessionDir);
  console.log(`tasks=${result.taskCount}`);
  for (const [packageName, count] of result.packageTaskCounts) {
    console.log(`${packageName}=${count}`);
  }
}

/**
 * Enumerates generated inventory file-batch markdown pages and loads those with matching severity scope.
 *
 * @remarks
 * I/O: lists and reads inventory pages under each `packages/<name>/fixes/file--*.md` path; never rewrites inventory artifacts.
 *
 * @throws When the `packages` directory is missing under the inventory root.
 */
function readInventoryBatches(options: CliOptions & { readonly inventoryRoot: string }): InventoryFileBatch[] {
  const packagesRoot = path.join(options.inventoryRoot, "packages");
  if (!existsSync(packagesRoot)) {
    throw new Error(`Inventory packages directory not found: ${path.relative(options.workspaceRoot, packagesRoot)}`);
  }

  const batches: InventoryFileBatch[] = [];
  for (const packageName of readdirSync(packagesRoot).sort()) {
    if (options.packageFilters.size > 0 && !options.packageFilters.has(packageName)) {
      continue;
    }
    const fixesRoot = path.join(packagesRoot, packageName, "fixes");
    if (!existsSync(fixesRoot)) {
      continue;
    }
    for (const fileName of readdirSync(fixesRoot).sort()) {
      if (!fileName.startsWith("file--") || !fileName.endsWith(".md")) {
        continue;
      }
      const pagePath = path.join(fixesRoot, fileName);
      const batch = parseInventoryFileBatch({ pagePath, packageName, options });
      if (batch.diagnostics.length > 0) {
        batches.push(batch);
      }
    }
  }
  return batches;
}

/**
 * Parses one `file--*.md` inventory page into package name, repo-relative path, and violation rows.
 *
 * @remarks
 * I/O: synchronous read of `pagePath`. Findings list is empty when no violation matches the severity filter even if the table exists.
 *
 * @throws When required `**Package**` or `**File**` markers are missing or malformed.
 */
function parseInventoryFileBatch(args: {
  readonly pagePath: string;
  readonly packageName: string;
  readonly options: CliOptions & { readonly inventoryRoot: string };
}): InventoryFileBatch {
  const markdown = readFileSync(args.pagePath, "utf8");
  const packageName = matchRequired(markdown, /\*\*Package\*\*:\s*`([^`]+)`/, `package in ${args.pagePath}`);
  const repoRelativePath = matchRequired(markdown, /\*\*File\*\*:\s*`([^`]+)`/, `file in ${args.pagePath}`);
  const violations = parseViolationsTable(markdown);
  const hasSelectedSeverity = violations.some((diagnostic) => severityMatches(diagnostic.severity, args.options.severity));
  const diagnostics = hasSelectedSeverity
    ? violations.map((diagnostic) => ({
        line: diagnostic.line,
        column: diagnostic.column,
        ruleId: diagnostic.rule,
        message: `${diagnostic.severity.toUpperCase()}: ${diagnostic.message}`,
      }))
    : [];

  return {
    packageName: packageName || args.packageName,
    repoRelativePath,
    inventoryPagePath: path.relative(args.options.workspaceRoot, args.pagePath).split(path.sep).join("/"),
    diagnostics,
    severities: violations.map((diagnostic) => diagnostic.severity),
  };
}

/**
 * Scans the `## Violations` section for markdown table rows and normalizes cells into violation objects.
 */
function parseViolationsTable(markdown: string): Array<{
  readonly rule: string;
  readonly line?: number;
  readonly column?: number;
  readonly severity: "error" | "warning";
  readonly message: string;
}> {
  const violationsSection = markdown.split("## Violations")[1]?.split("## Agent Workflow")[0] ?? "";
  const rows = violationsSection
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line.startsWith("| `"));

  return rows.map((row) => {
    const cells = splitMarkdownTableRow(row);
    const rule = stripBackticks(cells[0] ?? "unknown");
    const line = parseOptionalInteger(cells[1]);
    const column = parseOptionalInteger(cells[2]);
    const severityText = (cells[3] ?? "warning").trim().toLowerCase();
    const severity = severityText === "error" ? "error" : "warning";
    const message = stripMarkdownLinks(cells[4] ?? "Inventory violation");
    return { rule, line, column, severity, message };
  });
}

/**
 * Trims leading and trailing pipe characters, then splits a table line into trimmed cell strings.
 */
function splitMarkdownTableRow(row: string): string[] {
  const trimmed = row.replace(/^\|/, "").replace(/\|$/, "");
  return trimmed.split("|").map((cell) => cell.trim());
}

/**
 * Collects unique `AgentFleetPackPackageConfig` entries, attaching standards paths that exist on disk.
 *
 * @remarks
 * I/O: `existsSync` checks only; does not read file contents.
 */
function buildPackageConfigs(workspaceRoot: string, batches: readonly InventoryFileBatch[]): Map<string, AgentFleetPackPackageConfig> {
  const packageConfigs = new Map<string, AgentFleetPackPackageConfig>();
  for (const batch of batches) {
    const packagePath = batch.packageName;
    packageConfigs.set(batch.packageName, {
      packageName: batch.packageName,
      packagePath,
      taskIdPrefix: defaultPrefix(batch.packageName),
      standards: [
        "AGENTS.md",
        `${packagePath}/AGENTS.md`,
        "docs/TYPESCRIPT_STANDARDS_CODING_PATTERNS.md",
        "docs/TYPESCRIPT_STANDARDS_DOCUMENTATION_FILE_OVERVIEWS.md",
        "docs/TYPESCRIPT_STANDARDS_DOCUMENTATION_JSDOC.md",
        ".eslint-inventory/README.md",
        `.eslint-inventory/generated/packages/${batch.packageName}/README.md`,
      ].filter((candidate) => existsSync(path.join(workspaceRoot, candidate))),
    });
  }
  return packageConfigs;
}

/**
 * Builds one `AgentFleetPackTask` with inventory-backed diagnostics, rule counts, and agent-oriented guidance.
 */
function toTask(args: {
  readonly batch: InventoryFileBatch;
  readonly index: number;
  readonly packageConfigs: ReadonlyMap<string, AgentFleetPackPackageConfig>;
  readonly workspaceRoot: string;
}): AgentFleetPackTask {
  const packageConfig = args.packageConfigs.get(args.batch.packageName);
  const packagePath = packageConfig?.packagePath ?? args.batch.packageName;
  const packageRelativePath = path
    .relative(path.join(args.workspaceRoot, packagePath), path.join(args.workspaceRoot, args.batch.repoRelativePath))
    .split(path.sep)
    .join("/");
  const prefix = packageConfig?.taskIdPrefix ?? defaultPrefix(args.batch.packageName);
  const ruleCounts = countRules(args.batch.diagnostics);

  return {
    id: `${prefix}-${String(args.index + 1).padStart(3, "0")}-${agentFleetPackSlugify(packageRelativePath)}`,
    packageName: args.batch.packageName,
    packagePath,
    repoRelativePath: args.batch.repoRelativePath,
    packageRelativePath,
    title: `Fix ESLint inventory findings in \`${args.batch.repoRelativePath}\``,
    diagnostics: [
      ...args.batch.diagnostics,
      {
        ruleId: "eslint-inventory/context",
        message: `Inventory page: ${args.batch.inventoryPagePath}`,
      },
    ],
    ruleCounts,
    objective: `Fix the ESLint inventory findings for \`${args.batch.repoRelativePath}\`. Read the generated inventory page \`${args.batch.inventoryPagePath}\` before editing, including any linked rule-specific fix patterns.`,
    expectedApproach: [
      "- Treat `.eslint-inventory/generated/.../fixes/file--*.md` as curated backlog context, not as generated source to edit.",
      "- Fix the source file, not the generated inventory artifact.",
      "- If the inventory links a rule-specific fix pattern, follow it unless local code semantics require a safer equivalent.",
      "- Preserve behavior and documentation quality; warnings are not permission for superficial rewrites.",
    ].join("\n"),
    taskKind: "eslint-inventory",
  };
}

/**
 * Tallies how many times each `ruleId` appears so task metadata can summarize category counts.
 */
function countRules(diagnostics: readonly AgentFleetPackDiagnostic[]): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const diagnostic of diagnostics) {
    counts[diagnostic.ruleId] = (counts[diagnostic.ruleId] ?? 0) + 1;
  }
  return counts;
}

/**
 * Returns true when a violation severity should be included for the current `--severity` filter.
 */
function severityMatches(severity: "error" | "warning", filter: SeverityFilter): boolean {
  return filter === "all" || severity === filter;
}

/**
 * Strips a single leading or trailing backtick wrapper left over from inventory table formatting.
 */
function stripBackticks(value: string): string {
  return value.trim().replace(/^`|`$/g, "");
}

/**
 * Replaces `[text](url)` with `text`, then removes backticks so messages stay plain for agent prompts.
 */
function stripMarkdownLinks(value: string): string {
  return value.replace(/\[([^\]]+)\]\([^)]+\)/g, "$1").replace(/`/g, "").trim();
}

/**
 * Parses an optional table cell into an integer, yielding `undefined` for blank or unparseable input.
 */
function parseOptionalInteger(value: string | undefined): number | undefined {
  if (!value) {
    return undefined;
  }
  const parsed = Number.parseInt(value.trim(), 10);
  return Number.isFinite(parsed) ? parsed : undefined;
}

/**
 * Extracts capture group one from markdown or throws a parse error naming the missing field.
 *
 * @throws When the pattern matches nothing or group one is empty.
 */
function matchRequired(markdown: string, pattern: RegExp, description: string): string {
  const match = markdown.match(pattern);
  if (!match?.[1]) {
    throw new Error(`Could not parse ${description}.`);
  }
  return match[1];
}

/**
 * Maps known monorepo package folder names to stable short prefixes; otherwise derives from the slug.
 */
function defaultPrefix(packageName: string): string {
  const knownPrefixes: Record<string, string> = {
    "core-package": "CORE",
    "ui-package": "UI",
    "manager-next-package": "MNEXT",
    "manager-astro-package": "ASTRO",
    "sample-package": "SAMPLE",
  };
  return knownPrefixes[packageName] ?? agentFleetPackSlugify(packageName).replace(/-/g, "").slice(0, 10).toUpperCase();
}

/**
 * Parses argv tokens after the script name into validated `CliOptions`, using defaults for omitted flags.
 *
 * @throws On unknown switches, missing flag values, invalid enum tokens, or malformed numeric flags.
 */
function parseArgs(args: readonly string[]): CliOptions {
  let inventoryRoot = ".eslint-inventory/generated";
  let workspaceRoot = process.cwd();
  let outRoot = ".tmp";
  let purpose = "eslint-inventory-cleanup";
  let model = "composer-2";
  let severity: SeverityFilter = "all";
  let parallelStrategy: "package" | "none" | "bounded" = "package";
  let maxConcurrentTasks = 10;
  let maxConcurrentTasksPerPackage = 4;
  let agentLaunchDelaySeconds = 10;
  const packageFilters = new Set<string>();

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--help" || arg === "-h") {
      printHelpAndExit();
    }
    const value = args[index + 1];
    if (value === undefined) {
      throw new Error(`Missing value for ${arg}`);
    }
    switch (arg) {
      case "--inventory-root":
        inventoryRoot = value;
        index += 1;
        break;
      case "--workspace":
        workspaceRoot = path.resolve(value);
        index += 1;
        break;
      case "--out-root":
        outRoot = value;
        index += 1;
        break;
      case "--purpose":
        purpose = value;
        index += 1;
        break;
      case "--model":
        model = value;
        index += 1;
        break;
      case "--severity":
        if (value !== "all" && value !== "error" && value !== "warning") {
          throw new Error("--severity must be one of: all, error, warning.");
        }
        severity = value;
        index += 1;
        break;
      case "--package":
        packageFilters.add(value);
        index += 1;
        break;
      case "--parallel":
        if (value !== "package" && value !== "none" && value !== "bounded") {
          throw new Error("--parallel must be 'package', 'bounded', or 'none'.");
        }
        parallelStrategy = value;
        index += 1;
        break;
      case "--max-total-agents":
        maxConcurrentTasks = parsePositiveInteger(value, "--max-total-agents");
        index += 1;
        break;
      case "--max-package-agents":
        maxConcurrentTasksPerPackage = parsePositiveInteger(value, "--max-package-agents");
        index += 1;
        break;
      case "--agent-launch-delay-seconds":
        agentLaunchDelaySeconds = parseNonNegativeNumber(value, "--agent-launch-delay-seconds");
        index += 1;
        break;
      default:
        throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return {
    inventoryRoot,
    workspaceRoot,
    outRoot,
    purpose,
    model,
    severity,
    packageFilters,
    parallelStrategy,
    maxConcurrentTasks,
    maxConcurrentTasksPerPackage,
    agentLaunchDelaySeconds,
  };
}

/**
 * Parses CLI integer options that must be finite, safe integers strictly greater than zero.
 *
 * @throws When parsing fails or the value is below one.
 */
function parsePositiveInteger(value: string, flagName: string): number {
  const parsed = Number.parseInt(value, 10);
  if (!Number.isSafeInteger(parsed) || parsed < 1) {
    throw new Error(`${flagName} must be a positive integer.`);
  }
  return parsed;
}

/**
 * Parses CLI numeric options that must be finite and zero or positive.
 *
 * @throws When parsing fails or the value is negative or non-finite.
 */
function parseNonNegativeNumber(value: string, flagName: string): number {
  const parsed = Number.parseFloat(value);
  if (!Number.isFinite(parsed) || parsed < 0) {
    throw new Error(`${flagName} must be a non-negative number.`);
  }
  return parsed;
}

/**
 * Prints usage text to stdout and terminates the process with exit code zero.
 *
 * @remarks
 * Side effect: calls `process.exit(0)`; never returns to the caller.
 */
function printHelpAndExit(): never {
  console.log(`Generate a runnable Agent Fleet pack from .eslint-inventory generated markdown.

Usage:
  npx tsx skills/agent-fleet/scripts/generate-eslint-inventory-agent-fleet-pack.ts \\
    --inventory-root .eslint-inventory/generated \\
    --purpose eslint-inventory-cleanup \\
    --severity all

Options:
  --inventory-root PATH     Generated inventory root. Default: .eslint-inventory/generated.
  --purpose SLUG            Purpose slug for .tmp/<timestamp>-agent-fleet-<slug>/.
  --out-root PATH           Output root. Default: .tmp.
  --model MODEL             Agent Fleet model. Default: composer-2.
  --workspace PATH          Workspace root. Default: current directory.
  --severity all|error|warning  Include files with this severity; selected file tasks include all findings in that file. Default: all.
  --package NAME            Limit to package. Repeatable.
  --parallel package|bounded|none  Generate package, bounded, or no parallel runner. Default: package.
  --max-total-agents N      Bounded mode max active agents across all packages. Default: 10.
  --max-package-agents N    Bounded mode max active agents per package. Default: 4.
  --agent-launch-delay-seconds N  Bounded mode delay between launching agents. Default: 10.

Before running, refresh inventory when needed:
  npm run eslint:inventory
`);
  process.exit(0);
}

main();
